# Generated by Django 4.1.6 on 2023-02-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('last_editor_user_id', models.IntegerField(blank=True, null=True)),
                ('post_type_id', models.SmallIntegerField()),
                ('accepted_answer_id', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('answer_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('owner_display_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_editor_display_name', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('tags', models.CharField(blank=True, max_length=512, null=True)),
                ('content_license', models.CharField(max_length=64)),
                ('body', models.TextField(blank=True, null=True)),
                ('favorite_count', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('community_owned_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
