# Generated by Django 4.1.6 on 2023-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('up_votes', models.IntegerField(default=0)),
                ('display_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=512)),
                ('profile_image_url', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
                ('about_me', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('last_access_date', models.DateTimeField()),
            ],
        ),
    ]
