# Generated by Django 4.1.6 on 2023-02-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cqa', '0002_badges_comments_posthistory_postlinks_posts_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
