# Generated by Django 4.1.6 on 2023-02-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cqa', '0003_alter_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AlterModelTable(
            name='postlinks',
            table='posts',
        ),
    ]
