# Generated by Django 4.1.6 on 2023-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqa', '0005_posts_alter_postlinks_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('reputation', models.IntegerField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('down_votes', models.IntegerField(blank=True, null=True)),
                ('up_votes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('last_access_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
